config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :new, :create ]
  end
  delete '/doses/:id', to: 'doses#destroy', as: 'dose'
  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [ :new, :create ]

  def create
    @cocktail = Cocktail.find(params[:cocktail])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <h1 class="text-center">Discover Cocktail Recipes</h1>

  <div class="row">
    <h2 class="text-center">Trending</h2>

    <div class="row">
      <!-- Card -->
      <% @cocktails.each do |cocktail| %>

      <div class="col-xs-12 col-sm-4">
          <div class="card-description">
            <h2> <%= cocktail.name  %> </h2>
          </div>
          <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
      </div>
      <% end %>

      <div class="pad10">
        <%= link_to "Add cocktail", new_cocktail_path, class: "btn btn-primary pad20" %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div classS="container padded">
  <div class="card" style="width: 320px;>
    <div class="row">
      <div class="card-body">
        <h5 class="card-title">Add an ingridient</h5>
        <p class="card-text">Just add your favourite cocktails to the list.</p>
          <%= simple_form_for(@cocktail) do |f| %>
            <%= f.error_notification %>
            <%= f.input :name %>
            <%= f.button :submit, class: "btn btn-primary" %>
          <% end %>
        <%= link_to "Back", cocktails_path, class: "btn btn-warning btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1 class="text-underline"> <%= @cocktail.name %> </h1>


  <div class="pad10">
    <% if @cocktail.doses.empty? %>
    <p class="text-gray">
      No ingredients yet. Add yours!
    </p>
    <% else %>
    <h3> Ingredients </h2>
      <% end %>
  </div>

  <ul class="list-unstyled pad20">
    <% @cocktail.doses.each do |d| %>
    <li>
      <i class="fa fa-glass"></i> <strong> <%= d.ingredient.name %> </strong>
      <%= link_to "Delete", dose_path(d), class: "btn btn-danger btn-xs", method: :delete  %>
    </li>
    <p class="pad10"><%= d.description %></p>
    <% end %>
  </ul>
  <div class="pad20">
    <%= link_to "Add ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary", id: "ingredient-add-button"%>
    <%= link_to "Back", cocktails_path, class: "btn btn-warning" %>
  </div>


    <!-- Add cocktail form -->
    <div class="pad20" id="ingredient-form">
      <div class="row">
        <div class="col-xs-12 col-md-4">
          <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.input :ingredient, collection: Ingredient.order(:name),  prompt: "Pick one from list" %>
            <%= f.input :description %>
            <%= f.submit "Submit", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>

</div>

app/views/doses/new.html.erb
<div class ="container padded">
  <div class="card" style="width: 320px;>
    <div class="card-body">
        <h5 class="card-title">Add new cocktail recipes</h5>
        <p class="card-text">Just add your favourite cocktails to the list.</p>
          <%= simple_form_for @cocktail do |f| %>
            <%= f.input :name, placeholder: 'Zombie'%>
            <%= f.submit "Submit", class: "btn btn-primary" %>
          <% end %>
        <%= link_to "Back", cocktails_path, class: "btn btn-warning btn-sm" %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>